### ISSUE TITLE
Add NC6 support too please

### ISSUE THREAD

**Issue by is0Pristine** [acceleration3/cloudgamestream#13]
For some weird reason I cant make nv6 anymore, its not out of stock in my region, I cant make it in any region in fact, not even US, none,my student subscription works 100% since I can make nc6 and nc6 promo, please let me know if theres a way to get this script to work on nc6, thanks

**Comment by SoftwareRat** [comment]
Not possible since NC6 is using Tesla K80 GPU's and they don't support GRID

**Comment by acceleration3** [comment]
As @SoftwareRat said, this unfortunately isn't possible, sorry.
