### ISSUE TITLE
Resolution bug on windows 10

### ISSUE THREAD

**Issue by Eleveres** [acceleration3/cloudgamestream#16]
Here are the steps I've followed on a fresh windows 10 pro install on google cloud:
1) Install the version 442 of the GRID drivers (only one that seems to work with your patch on windows 10)
2) Install the audio driver
3) Install parsec 
4) Configure autologin
5) Run your patch

When I run your patch and I get to the NvFBC part, my screen resolution changes to 1300 x 900 and the resolution fix doesn't fix it. After I reboot the machine and connect with parsec my resolution is fine again. At that point I disconnect from parsec and connect with moonlight and the resolution is back to 1300 x 900. I can however change it to a normal resolution back again. Now everything works fine and I'm able to play games through moonlight. But once I reboot the machine and try to connect with moonlight I'm back to a 1300 x 900 resolution but this time Windows doesn't let me change the resolution. And if I reboot the machine and try connecting through parsec my resolution is still stuck. The only solution is to disable gamestream and reboot the machine once again.

**Comment by acceleration3** [comment]
Thank you for your patience and for allowing me to access the VMs! This issue should be fixed with the newest version but I will await your confirmation to close this issue.
