### ISSUE TITLE
The EDID hack seems to do more harm than good

### ISSUE THREAD

**Issue by GregRos** [acceleration3/cloudgamestream#2]
the EDID hack sets the max display resolution to around 1080p and won't let you play games at 1440p. I had to unload the EDID to unlock the resolution and didn't encounter the problem you describe.

Otherwise this hack works incredibly well! Moonlight + this is by far the best streaming solution out of everything I tried, way better than both steam remote play and Parsec.

My server is Google Cloud, N1 4vcore 15GB /w T4 (+ GRID) running Windows Server 2019 datacenter in europe-west3-b

**Comment by acceleration3** [comment]
Thanks for reporting, I will try to look for a better solution.
