### ISSUE TITLE
g4dn now throws exception on GRID driver install

### ISSUE THREAD

**Issue by samAnnisBrown** [acceleration3/cloudgamestream#4]
I've tried to run on a g4dn instance in AWS, and on both Windows 2016 and 2019 I get an exception on the GRID drivers.

This is a fresh install of both, and am connected using AnyDesk.

Running the driver manually in interactive mode, I can see it cannot detect any NVIDIA GPU hardware.  Interestingly, the AWS GRID drivers install just fine.

Not sure if something has changed in the past month or I'm doing something wrong, but seems like an issue with the driver being used.

**Comment by acceleration3** [comment]
I plan on making this script use the GPU Updater script as a fallback when the default driver install fails which should fix this issue.

**Comment by JRagone** [comment]
I can confirm the same issue on GCP with a T4 on Windows 2016 and 2019, though I suppose it shouldn't be different from AWS anyways. Installing the driver manually leads to a failed hardware check.

**Comment by acceleration3** [comment]
I think this should be fixed with the latest commit. I'll wait for confirmation to close this issue.

**Comment by samAnnisBrown** [comment]
I can confirm that on a g4dn instance it will fall back to the GPU updater script if GRID fails - looks good to me :)
